[PlankDockPreferences]
Alignment=1
AutoPinning=true
CurrentWorkspaceOnly=false
HideDelay=250
HideMode=1
IconSize=28
ItemsAlignment=1
LockItems=true
Monitor=''
Offset=0
PinnedOnly=true
Position=3
PressureReveal=false
Theme=Transparent
UnhideDelay=200
ZoomEnabled=false
ZoomPercent=100
