backend = "xrender";
vsync = false;

shadow = true;
shadow-radius = 20;
shadow-opacity = 0.30;
shadow-offset-x = -10;
shadow-offset-y = -10;

shadow-exclude = [
  "window_type = 'dock'",
  "class_g = 'Plank'"
];

corner-radius = 14;
round-borders = 1;

fading = false;

inactive-opacity = 1.0;
active-opacity = 1.0;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
